# Generated by Django 3.2.7 on 2021-09-14 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Filename', models.CharField(max_length=256)),
                ('InsertedAt', models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 14, 19, 58, 38, 812756, tzinfo=utc))),
                ('LocalPath', models.CharField(max_length=256)),
                ('S3Path', models.CharField(max_length=256)),
                ('Tag', models.CharField(max_length=256)),
            ],
        ),
    ]
