# Generated by Django 3.2.7 on 2021-09-14 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoRepoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='InsertedAt',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 14, 20, 2, 0, 187933, tzinfo=utc)),
        ),
    ]
